os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgfortran3 liblapacke-dev libopenblas-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openblas || true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lapack || true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap AdoptOpenJDK/openjdk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install adoptopenjdk8; fi

script: ./gradlew build --info


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan
    - $HOME/Library/Caches/Homebrew
